### ISSUE TITLE
Des nouveaux bugs, pour votre plus grand plaisir

### ISSUE THREAD

**Issue by Alcarioz** [lespetitspedestres/EnGarde#11]
- [x] Lors d'une attaque, cumuler les cartes d'attaque est impossible.
- [x] Les attaques indirectes sont impossibles à réaliser dans la plupart des cas.
- [x] Crash du jeu quand un des joueurs est un humain, s'il il clique pour un mouvement, il peut encore 
      cliquer ailleurs, et le jeu plante s'il le fait.
- [x] Attaque directe: si le joueur subissant l'attaque pare, il ne peut rien faire derrière, s'il annule la parade, 
  il peut se déplacer librement malgré l'attaque directe qu'il subit. Cependant les IA semblent réussir les 
  parades.
- [x] Contre l'IA, n'affiche pas la carte jouée par cette dernière, sinon, dans certains cas, cumule les cartes 
   jouées.
- [x] Déplacement léger du nom du joueur 1.
- [x] Affichage erroné du journal en fin de partie.
- [x] Abandon ne marche plus.
- [x] A la fin d'une partie, s'il l'on rejoue, pendant la première manche, les cartes du joueur 2 ne s'affichent 
  pas.

Selon Yohan: "CELA PROVIENT QUASIMENT TOUT DU MÊME BUG."

**Comment by visagey** [comment]
Selon moi, oui, les quatre premiers bugs sont liés : la régression a été introduite dans 283bf97ce5eb9aff87498d4e413fb3a58d477547, et j'en suis bien désolé.
Le problème semble réglé dans 69751b3002c246390841945d28a5bdf863d7ad64.

Pour le cinquième point, j'ai proposé à @MackValentine de gérer ça côté moteur, et il n'aura plus qu'à réutiliser la méthode `getUserChoice()` pour obtenir la liste des cartes jouées.

Pour l'avant dernier point, c'était aussi de ma faute. Régression introduite dans ecd21fb9c69068d798be409a1a4965e2dd19c563, corrigée dans 0283c79cc4aa243ff68116259296e1545287c061. Il est possible d'abandonner uniquement quand c'est à soi de jouer.

Autre bug :
- [ ] En IA vs IA, les cartes sont absentent et s'affichent **après** le coup du premier joueur qui joue. Idem en réseau : au premier tour, le joueur qui attend la sélection de l'autre joueur n'a pas de cartes.

**Comment by visagey** [comment]
Après un bref coup d’œil, le décalage du pseudo du J1 est apparu dans 8e5ac13bd95287aa010661b8a2711caaf47f6b34. Ce genre de mésaventure ne se produirait pas avec des constantes... C'est corrigé dans cace4bb4d9586a84be506e7f1a46757414aa22e6.

BTW, tu m'as l'air de faire énormément de duplications de lignes de code @MackValentine, exemple :
```
if (engine.getCurrentPlayer() == player) {
	g2.drawString(s, 30, 537);
	g.drawImage(arrows.getSprite(1, 0), 16 + 4, 537 - 8, 5, 10, null);
} else {
	g2.drawString(s, 30, 537);
}
```
Peut s'écrire en :
```
g2.drawString(s, 30, 537);
if (engine.getCurrentPlayer() == player) {
	g.drawImage(arrows.getSprite(1, 0), 16 + 4, 537 - 8, 5, 10, null);
}
```
Je dis juste ça comme ça, c'est pas bien grave.

Il faut que je nettoie le code du moteur à certains endroits. :>

**Comment by MackValentine** [comment]
Yep, sur ce genre de truc, c'est parce que c'était la méthode appelé pour afficher qui étais pas la même. J'ai juste pas pris le temps de nettoyer cette aprem.
 ( Et je préfère faire tout d'un coup )
Le journal en fin de partie, ça sera corrigé en 5 minutes,

Je jette un œil à tout ça demain.

**Comment by visagey** [comment]
Je ne sais pas si c'est lié, mais il y a un gros soucis en IA vs IA, car tu n'affiches pas les bonnes cartes pour le J2, alors que le J1 c'est bon.
Pour le J2, tu sembles utiliser `getPlayerHand()` au premier tour, et quand tu appelles `getPlayableCards()` pour le J2, tu n'utilises visiblement pas la valeur de retour (c'est ce que j'observe avec les messages de debug du moteur), donc on voit toujours les cartes initiales du J2.

À mon avis, mais je me trompe peut-être, tu t'es trop pris la tête pour les scènes de jeu. C'est un peu de ma faute, je t'ai laissé te débrouiller tout seul sans t'indiquer comment j'attendais que tu utilises le moteur. Il faudrait que je documente comment écrire une boucle principale qui utilise le moteur, selon les différents scénarios.

**Comment by visagey** [comment]
Par rapport au cinquième point, après étude de la chose, j'ai changé mon projet. Ça me paraît plus naturel que ça soit `validateCards()` qui renvoie la liste des cartes jouées ; actuellement, cette méthode renvoie une attaque, et tu as besoin de cette attaque pour pouvoir faire tes animations, soit.
C'est pour cela que dans b26973bf28c95c391b6f9aea08f85b30cedcef3e, j'ai légèrement modifié la classe Attack : après ton `validateCards()`, tu n'auras qu'à utiliser `getCardsUsed()` sur l'attaque retournée pour obtenir la liste des cartes qui viennent d'être jouées.

J'ai fais un petit changement dans d66a35198d578c7f7c9f339759013925dfd4514e pour que `validateCards()` te retourne une copie de l'attaque, ça devrait éviter les effets de bords quand l'autre joueur joue.
