### ISSUE TITLE
Ajout de boutons sur l'écran titre

### ISSUE THREAD

**Issue by visagey** [lespetitspedestres/EnGarde#12]
@lespetitspedestres/team-ihm 
L'écran titre est encore loin d'être dans son état final, et il faudrait ajouter les boutons suivants :
- [x] Tutoriel / Didacticiel
- [x] Règles / Aide
- [x] Statistiques
- [x] Crédits / À propos

Bien sûr, ce ne sont que des propositions de noms, rien de définitif.

* Pour le tutoriel, j'ai vaguement commencé à mettre en place des choses côté moteur, mais il faudrait faire des choses côté IHM (scène spéciale ?).
* Pour les règles, j'avais proposé de m'en charger.
* Pour les crédits, simplement mette les noms des gens du groupe, et des remerciements (tutrice, profs, etc...).

**Comment by MackValentine** [comment]
Yep pour le didacticiel faudrait qu'on voie ça ensemble Lundi, voir comment on s'y prend.
J'regarde pour rajouter les boutons sur l'écran titre, et commencer les scènes des 3 autres parties demain.

**Comment by visagey** [comment]
Pour l'instant, j'ai mis en place le scénario suivant pour le didacticiel : [scénario](https://github.com/lespetitspedestres/EnGarde/blob/master/docs/Didacticiel.pdf).

Dans l'idée, j'imaginais que les pseudos seraient pré-définis, et que ça serait sans doute une nouvelle scène.
En gros, pour démarrer le didacticiel côté IHM :
```
engine = new Engine("Champion", PlayerType.HUMAN, "Adversaire", PlayerType.TUTORIAL);
```

On verra ça demain.

**Comment by Amebannin** [comment]
pour le deck l'odre des carte de la partie de didacticiel c'est 5 4 4 2 1 4 5 4 2 2 1 2 3 5 3 4 3 3 3 1 1 5 1 2 5

et l'odre de jeu des carte c'est j1 qui commence

et on joue + = avancer
                 / = defendre
                 - = reculer
                 * = attaquer
                 j1: +5                j2 : +4
                 j1: +4                j2 : +5
                 j1: *4                 j2 : /4 +2 *2
                 j1: /2 +1 *1       j2 : -2
                 j1: *3*3*3

cela prend tout les cas de figure déplacement, attaque direct, attaque indirect paré et esquiver et aussi l'attaque multiple

**Comment by visagey** [comment]
Non mais je t'explique : le didacticiel est finalisé depuis hier, voir commit f2ccaf4b56156617b0baba5affcf8580902218f5.
Donc c'est bien beau de proposer des choses qu'on a déjà fait !
