### ISSUE TITLE
Amélioration de la fenêtre de jeu en réseau

### ISSUE THREAD

**Issue by visagey** [lespetitspedestres/EnGarde#13]
Je crois que j'étais très fatigué hier, impossible de corriger les changements sur la partie réseau. 😿 
Un peu de sommeil et ça va tout de suite mieux : 3a428d99daaf1f762f510bbc613e467952860ddf. Maintenant que la branche *broken* est réparée, je l'ai fusionnée dans *master* (fc1d85447db6123cb1415f1e9aaaad6a4f62f64e).

Enfin bref, voilà ce qu'il reste à faire :
- [x] Réorganiser la page de connexion
- [x] Laisser la case cochée quand on démarre le serveur (bon, c'est cosmétique, donc ce n'est pas très important au pire)
- [x] Informer le joueur (serveur) quand il ne peut pas démarrer le serveur
- [x] Informer le joueur (client) quand il ne peut pas se connecter au serveur demandé
- [x] Retenir les choix (checkbox et labels)

J'ai vaguement modifié la classe SceneMultiplayer pour générer des pseudos par défaut s'ils ne sont pas définis, et mettre "localhost" si la variable `p1` sur le client est indéfinie, mais je te laisse le soin de t'occuper du reste.

**Comment by Amebannin** [comment]
je m'occupe demain de la reorganisation de la page de conection en plus des boutton du menu je les acheve cet aprem normalment.
je ferais plusieur version des bouttons (differente écriture, différent fond etc.... comme ca vous pourrez voté pour celui que vous voudrez

**Comment by MackValentine** [comment]
Déjà tout fait.
