### ISSUE TITLE
[IHM] Cartes de l'adversaire / Crédit / Stats

### ISSUE THREAD

**Issue by MackValentine** [lespetitspedestres/EnGarde#14]
A faire :
- [x]  Page de crédit
- [x] Page de stats
- [x] Finir les règles.
- [x] Corriger le bug des cartes du P2
- [x] Quitter le menu avec échap
- [x] Problème avec les cartes lors du didacticiel.

**Comment by visagey** [comment]
Les règles, c'est à peu près bon : 68c88d28472c11ffe98d47a7234405285b09bd62.
À voir demain qu'est-ce qu'il faut améliorer.

**Comment by visagey** [comment]
Crédits c'est bon : 5beb16f1a739cfa69070ffd878776f40daaeefc6.
Stats c'est bon : e1960a8991db16cd599060b69f4c51df35b6239d.
Echap c'est bon : 455ed036c234165be2c39e9521f1bd7f4a8553bf.
