### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by Jonathan-Granier** [lespetitspedestres/EnGarde#15]
Retour utilisateur :  
L'ecran entre chaque manche est bizzare , le vainqueur est ecrit en petit et le gros texte : "en attente du joueur suivant" à pas vraiment de sens.

Le journal devrait etre aligné (en fonction de la taille du plus grand nom des 2 joueurs) pour qu'il soit un peu plus lisible.
En IA contre IA , on a du mal à savoir qui joue , l'interface clignote de partout . 
C'est difficile de savoir quelles cartes on a pioché entre chaque tour. 
(Les cartes sont coupées en bas mais j'imagine que j'ai pas la bonne version). 

Au niveau des régles , du vert sur du vert c'est pas ouf (Onglet "Avancer").
Pareil pour le orange dans l'onglet "Jeu" , "Information manche" est presque invisible.

Quand on agrandie la taille de fenetre la qualité des textes devient dégeu.  

C'est bizzare d'acceder aux options . Une fois le bouton est bien distinct des autres , une autre il est confondu .
Le bouton fermeture est un peu ambigu. On dirait qu'il va fermer la fenetre du menu et non le jeu. 
On pourrai mettre genre "Quitter le jeu" à la place.

BUG : 
Dans l'onglet Jeu en réseau si je fait : 
Je coche jeu en réseau
Je clique sur connexion
Je clique sur Retour
Je clique sur Jeu en réseau
Je coche jeu en réseau 
J'obtient : Port non disponible.

Voila voila 
Les remarques ne sont que l'avie d'un utilisateur.

**Comment by visagey** [comment]
Ok, merci beaucoup pour ton retour Jonathan.

- Ouais, @MackValentine va s'occuper de l'écran noir en fin de manche : c'est juste de recyclage de code, mais faudrait qu'il le change.
- Par rapport à ce que tu dis sur "on ne sait pas qui joue", c'est pas faux : @MackValentine va ajouter une marque au dessus du joueur actuel pour le mettre en évidence ; je pense que ça sera présent dans la release de ce soir.
- C'est vrai ça, on ne sait pas quelles cartes ont été piochées : on peut le savoir en console avec la variable d’environnement `ENGARDE_DEBUG_LEVEL=ENGINE_TYPES_DECK`, mais je t'avoue qu'il n'y a pas de méthode au niveau du moteur qui peut remonter cette information à l'IHM, et on est trop proche de la fin du projet pour se permettre ce genre de "grosse modification". On aurait dû le prévoir plus tôt... C'est ajouté à la liste des améliorations possibles.
- Pour les couleurs dans les règles, oui ce n'est pas fou, j'avais mis du gris avant à la place du orange et c'était pire. Je suis pas un pro de Gimp, j'ai fait ça moi-même, mais comme j'ai dit aux autres, c'est améliorable, les .xcf sont sur le dépôt, ils peuvent donc facilement changer ça.
- Quand on agrandit, il n'y a pas que les textes qui deviennent dégueu. :>
- D'accord pour le "Fermeture", j'avais eu la même réaction. On va opter pour un "Retour bureau" à la place, plus explicite.
- Pour la partie réseau, c'est corrigé dans aa9a74455623fa88a77ca4615557c26e8d47dc33. Merci bien !

**Comment by Jonathan-Granier** [comment]
De rien :)

**Comment by visagey** [comment]
Voilà, certains textes dans les boutons ont été modifiés, l'écran noir de fin de manche a été revu, et le joueur courant a maintenant un triangle rouge au dessus de la tête.
Si tu as besoin de re-tester, tu sais où trouver la dernière archive JAR exécutable : [c'est ici](https://github.com/lespetitspedestres/EnGarde/releases/latest).

Je clos l'issue, mais n'hésite pas à la rouvrir si tu re-testes et que tu vois d'autres défauts. ;)
