### ISSUE TITLE
Demande d'améliorations pour l'IHM

### ISSUE THREAD

**Issue by visagey** [lespetitspedestres/EnGarde#17]
Je continue d'être chiant.

- [x] En jeu, quand on clique sur le bouton Menu, il faudrait pouvoir le fermer en re-cliquant dessus.
- [x] Mettre quelque part la liste des raccourcis claviers/souris (touche espace, touche F11, clic droit, etc...).
- [ ] Refaire l'image de fond de l'écran titre : il me semble que tu voulais changer de police, et que tu voulais rajouter des nuages. Je trouve qu'il manque quelque chose dans ce que j'ai fait, ça fait un gros trou entre le titre du jeu et les boutons...
- [x] Dans les statistiques, corriger le "Nombre moyen de manches" en "Nombre moyen de manches par partie", et corriger les alignements.
- [x] Ajouter une option pour **voir les cartes de l'IA** (ça a été demandé pendant les audits d'IHM).
- [x] Faire un fichier de configuration. Limite, on peut le faire conjointement. Mais couper la musique à chaque fois qu'on ouvre le jeu, c'est fatiguant à la longue. 😿 
- [x] Dans le didacticiel, à partir du deuxième tour, toutes les cartes sont grises. Bug IHM ou moteur ?

Et puis le reste ça ma paraît tout bon, j'ai fait un tour, tout m'a semblé OK.

**Comment by MackValentine** [comment]
Je regarde tout ça demain ;D.
J'en profite pour rajouter ça : 
- [ ] Corriger l'intégration des polices. 

( Chez moi impossible de lancer le jeu à cause de la police, donc va falloir que je trouve une solution )

**Comment by visagey** [comment]
Ah oui mince. Ça tourne sous GNU/Linux, macOS, mais Windows ne veut rien savoir. On peut dire que Windows ne respecte pas la police. 😸 
Boarf, j'ai farfouillé sur Internet, je n'ai pas réussi à résoudre ce problème. L'histoire de le rendre moins gênant, j'ai fait ça : 68465eee834f6e072ee4cb39dc4a23c93700fa30.

Autre "bug" intéressant : quand on désactive la sortie audio principale dans Windows (ce qui est le cas dans ma VM), il y a des exceptions au niveau du son, et le jeu ne se lance pas.

**Comment by visagey** [comment]
Je viens vite fait de faire ça : 6f9b2080a7396e88d8e0cc893f8b0775e484b769.
Le fichier de configuration perso est prioritaire sur celui par défaut. J'ai appliqué le changement que pour les sons.

Tu as la méthode `Configuration.getPropertieBoolean("propriété")` si tu veux t'occuper des autres propriétés, comme par exemple le plein écran.
À voir si ça t'intéresse d'ajouter une option pour activer ou désactiver les animations (pour remplacer la variable d'environnement).

**Comment by MackValentine** [comment]
Mouais. J'ai changé pas mal de truc, à voir ce qu'on garde : 

Par contre, pourquoi mettre le fichier de config super loin ? On a pas d’installateur, donc pour retirer le fichier faut savoir où il est. Donc c'est super relou. Autant le garder à côté du jeu, c'est beaucoup moins contraignant.

Ensuite j'ai modifié un peu le truc pour qu'on puisse sauvegarder le nouveau contenu des properties, ce qui évite de créer le fichier à la main.

Pour les animations, je sais pas trop. J'en avait discuter avec Ben je crois, et je pensais que c'était pas ouf. Après, ouais je peux toujours le rajouter et on verra Lundi si on garde.

Pour le son, il faudra que tu ré-éssaie, j'ai modifier un truc, ça devrait être mieux.
( Mais perso j'ai rien de ce genre, donc si tu l'as de nouveau, fais un screen de l'erreur )

**Comment by MackValentine** [comment]
Pour le dernier point, je pense que c'est un problème moteur, getCardUsage() me renvoi NONE sur toute les cartes, tout le temps, alors qu'il ne devrait pas.  Et comme c'est le même code que pour Joueur VS IA, et que là ça ne bug pas :/. Faudrait qu tu regardes si tu vois rien côté moteur, et sinon qu'on se capte Dimanche pour trouver.

Pour les raccourcis, j'ai rajouter un petit bandeau dans le menu Option.
Les stats, j'ai coupé la ligne en deux, ça me semble pas trop mal, mais à voir.
Pour les cartes de l'IA c'est dispo dans le menu Option maintenant.

Je jette un oeil pour les animations, et je verrais pour refaire l'Accueuil ce soir ou demain.

**Comment by visagey** [comment]
- Oui, tu as raison pour le fichier de configuration, je ne savais pas où le mettre, et vu que j'ai choppé le code du casse-briques, je ne me suis pas trop posé de questions.
Bien vu pour la modification automatique du fichier de configuration, c'est tout de suite beaucoup plus pratique. 👍 

- Non mais ne t'inquiète pas pour le son, je disais ça comme ça, je n'attends pas de fix, c'est assez vicieux comme cas :
![Son désactivé dans Windows](https://cloud.githubusercontent.com/assets/23583090/26504411/ce5dc53a-4244-11e7-903a-4db9f4e8e72e.png)
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
        at javax.sound.sampled.AudioSystem.getLine(Unknown Source)
        at javax.sound.sampled.AudioSystem.getClip(Unknown Source)
        at gui.Sound.create(Sound.java:38)
        at gui.windows.MainPanel.<init>(MainPanel.java:35)
        at gui.windows.MainFrame.<init>(MainFrame.java:63)
        at gui.windows.MainFrame.main(MainFrame.java:285)
        ... 5 more
```

Il suffit juste d'activer le son dans Windows pour contourner le problème :
![Son activé dans Windows](https://cloud.githubusercontent.com/assets/23583090/26504536/3d21fda6-4245-11e7-8859-12d1b6d5fee9.png)
Rien de bien méchant.

- Pour le "bug" des cartes dans le didacticiel, ça peut être corrigé dans le moteur (fait dans 79bf054bd4f65f646350e141b3c3c961b35d1877). En théorie, je n'avais pas prévu que tu utilises les méthodes pour récupérer les cartes comme ça... J'avais ajouté la méthode `getPlayerHand()` juste pour que tu puisses afficher les cartes de l'adversaire en mode IA vs IA, mais je n'avais pas prévu que tu l'utilises de partout.
En gros, ce que j'avais prévu, c'était que tu utilises `getPlayableCards()` pour obtenir les cartes du joueur en début de tour, puis `playACard()` à chaque sélection du joueur. `getPlayerHand()` est censée retourner le jeu tel quel, **sans le redécorer**, d'où pourquoi je réservais cette méthode pour du IA vs IA.
Maintenant, ça fonctionnait correctement de partout sauf dans le didacticiel par **effet de bord** ; la méthode `decorateCards()`, que j'utilise en fin de tour, est à double usage : je m'en sers pour redécorer les cartes du joueur courant, mais aussi pour vérifier que  le joueur suivant ne sera pas bloqué. J'ai fait ça pour éviter de dupliquer du code.
Le "bug" était visible dans le didacticiel car je n'utilise pas cette méthode dans le cadre du didacticiel pour vérifier la fin de la partie.
Bon, ce n'est pas grave, ça fonctionne correctement, ce n'est pas la peine de changer des choses, je me suis adapté.

Super tout ça, c'est du beau travail !
Pour les cartes de l'IA, je crois que tu as zappé le cas d'une partie en réseau : les cartes de l'adversaire deviennent visibles quand on joue, mais elles sont cachées quand il joue. J'aurais tendance à dire qu'il faudrait que ça cache tout le temps ses cartes.

**Comment by MackValentine** [comment]
Ah, j'pense que je sais pourquoi pour le son, j'vais regarder.

Par contre pour le réseau, j'pensais que ça allait être bon xD.
J'vais regarder ça correctement demain.

**Comment by MackValentine** [comment]
Ayé, j'ai corriger le bug de son, et le bug des cartes.

Du coup, bah je m'occupe du Logo d'ici Dimanche, et je pense qu'on a tout de bon.

**Comment by visagey** [comment]
Je n'ai pas de soucis de performance avec le menu.

Ok, je ferrai un nouveau test plus tard pour le son, mais en voyant le patch ça me paraît correct.
Par contre, **grosse régression** : le bouton abandonner ne fonctionne plus. Ça donne bien les points, mais ensuite le jeu se bloque. Bug constaté en PvP (local et réseau) et PvE.
J'ai juste fait ça c0f33ea57b92798ef87239d96c1029a58735f6a8 pour dégriser le bouton abandonner en réseau (et j'ai aussi renommé la méthode `getHostStatus()` en `isNetworkActive()`, car son nom n'était pas du tout parlant).

Oui, je pense aussi que ça sera tout bon niveau moteur et IHM. Niveau IA c'est moins sûr... 😆 
Ça serait bien que les autres fassent des retours aussi.

**Comment by MackValentine** [comment]
Apparemment, ça vient de ma fonction resetTiles(); dans SceneGame.
J'ai bidouiller pour corriger le problème, mais aucune idée de pourquoi ça a fait ça xD.

**Comment by visagey** [comment]
Yep, c'est bon, ça remarche.
Je corrige quelques bugs sur la partie réseau là (genre quand un joueur se déco, si c'est à lui de jouer, hé bah l'autre il peut attendre longtemps, trèèèèèèèèèèès longtemps).

Ahah, on ne peut plus fermer le menu avec la touche Echap maintenant. Nouvelle régression ! 😸

**Comment by visagey** [comment]
Problèmes réseaux résolus dans 7a0ee4bcd904549e67114ba31302fc76e4045837 : on peut maintenant fermer la fenêtre comme un gros bourrin, et l'autre joueur sera déclaré vainqueur.

J'ai voulu griser le bouton "Rejouer" à la fin d'une partie si l'autre joueur s'est déconnecté dans 8ed3bae006b2dca2157eb910f14ca5e0276ec88e. Le bouton n'est pas cliquable mais il n'est pas de la bonne couleur. Une idée ?

**Comment by MackValentine** [comment]
Du coup j'ai corriger les deux bugs ci dessus, mais chez moi ça bug toujours autant ( voir plus xD ) quand je coupe l'un des deux joueurs xD.
Que ça soit en fermant la fenêtre comme un porc, ou en cliquant sur retour à l’accueil, le jeu crash d'un des deux côtés xD.

J'ai aussi trouvé un autre bug IHM : 
En réseau, quand on est en fin de game et qu'on ouvre le journal, puis qu'on le ferme, la fenêtre de fin de jeu ne se ré ouvre pas, et le menu bug totalement.

**Comment by visagey** [comment]
Super tout ça.

Boarf, ça m'étonne un peu tout ça, j'ai justement fait plein de tests de bourrin chez moi et dans aucun des cas je n'ai eu de crashs. Je vais investiguer...

Autre petit soucis : en fin de partie, il n'y a pas l'écran noir qui apparaît, mais directement la fenêtre de fin de partie qui s'affiche (et du coup, mis à part en ouvrant le journal, on ne sait pas pourquoi on vient de gagner).

**Comment by MackValentine** [comment]
Yep, essaie de voir :/.

Si c'est seulement en réseau que l'écran apparaît pas, c'est bon, c'est réglé avec le problème du journal.
J'vais quand même jeter un oeil dans les autres modes pour vérifier que c'est bon.

**Comment by MackValentine** [comment]
Pour l'écran noir, ça devrait être bon maintenant, j'pense avoir réglé tout les bugs qu'il y avait.

**Comment by visagey** [comment]
Ah oui, effectivement, j'ai généré un JAR, et quand il tourne sous GNU/Linux j'ai pas de soucis en réseau, mais dans les mêmes conditions sous Windows ça plante.

Je confirme, le bug de l'écran noir est résolu.

**Comment by Alcarioz** [comment]
J'ai regardé un peu tout ce que vous avez fait, et je suis donc reparti faire ma fouine pour trouver des bugs, j'en ai pour le moment deux avec le menu in-game (possible que ça vienne du fait que je suis sur Windows cependant):

- Quand j'ouvre en partie le menu, puis que je clique sur "sauvegarde", si je clique sur "annuler" dans la fenêtre qui s'ouvre, cela clique aussi sur "retour bureau", le bouton "annuler" étant superposé sur ce dernier.

-Toujours dans le menu, si je clique sur le bouton "chargement", il arrive parfois que le jeu m'ouvre les options sans aucune raison.

A voir donc si cela vient juste de mon côté.

**Comment by visagey** [comment]
En parlant de la sauvegarde, elle ne fonctionne plus du tout ! Il semblerait que le JFileChooser ne soit pas correctement initialisé car il retourne toujours null après avoir validé et les filtres ne sont pas appliqués.

**Comment by Alcarioz** [comment]
Oui, je viens de m'en apercevoir aussi de la sauvegarde qui ne marche plus.
Mis à part ces trois problèmes, je n'en ai pas rencontré d'autres pour le moment.

**Comment by visagey** [comment]
C'est déjà pas mal. Pauvre Roux, à chaque fois qu'il croit qu'il touche au but, on lui en rajoute une couche. x)
Merci pour ces retours messire Gaunvain !

**Comment by MackValentine** [comment]
Ah, pour la save j'avais cru que ça venait de Windows xD.
Bon, bah, je vais jeter un œil à ça avant demain soir ^^.

**Comment by Alcarioz** [comment]
Bon du coup, me semble pas avoir trouvé d'autres bugs, en jeu local, hormis les bugs déjà annoncés, tout semble normal, avec ou sans IA.
En réseau, pas de bug a signaler en plus,  juste le problème de l'un des deux joueurs quittant brutalement la partie aussi, ça vient sans doute de windows du coup si de ton côté ça fonctionne bien Yohan.

Du coup, j'en ai profité aussi un peu pour faire une batterie de tests pour le dossier IA, et donc j'ai les résultats suivants:
Sur un échantillon de 100 rounds, l'IA moyenne bat 68% du temps l'IA facile.
Sur un échantillon de 50 parties, l'IA moyenne gagne 70% du temps contre l'IA facile.

Voilà voilà, je continuerai sans doute de regarder demain. Bonne soirée messires!

**Comment by visagey** [comment]
Non mais ce genre de bug est intéressant, ça permet de voir que le code n'est pas robuste.
Par exemple, t'es en réseau, tu demandes à recevoir un entier, et puis cet entier tu le convertis en un type énuméré (un code). Hé bah quand tu t'appelles Yohan, tu ne penses pas à vérifier que la socket est valide AVANT de convertir ton entier. Du coup, ça donne un fix comme celui-ci après s'être penché sur le problème : ff4d51539ce9d48f2ff72fdddc45db5d972d7d17. x)
J'ai retesté sous Windows, et le problème semble réglé.

BTW, pour le journal, je vais trouver une solution. C'est vrai que j'avais pas pensé à ce cas de figure avec le undo-redo. Avec un buffer temporaire ça devrait le faire. Merci Benji, testeur chevronné hors-pair !

**Comment by Alcarioz** [comment]
En effet, le problème est résolu en réseau, la partie prend bien fin quand l'un des joueurs quitte.
Deux petits trucs cependant:

Si un joueur quitte pendant le tour de l'autre, ce dernier doit quand même finir son tour avant que la partie ne prenne fin. (Je sais pas si on peut y faire grand chose)
De plus, toujours en réseau, si un joueur fait un déplacement qui lui permettrait de faire une attaque indirecte, mais finit son tour seulement avec le déplacement, pendant que le second joueur effectuera son tour, le premier aura toujours l'indication visuelle du petit triangle blanc en dessous du joueur adverse (mais ce dernier ne sera pas cliquable.)

Mis à part ça, vous avez fait du bon boulot, rien d'autre à signaler.

**Comment by visagey** [comment]
> Si un joueur quitte pendant le tour de l'autre, ce dernier doit quand même finir son tour avant que la partie ne prenne fin.

Ça restera tel quel, c'est le comportement désiré : pendant qu'un joueur joue, il n'y a pas d'interaction réseau, et donc si un joueur se déconnecte, le joueur qui est en train de jouer n'en n'est pas notifié.
Il valide, ça envoie son coup à l'autre joueur : une IOException est levée vu que l'autre joueur est déconnecté, mais le jeu continue normalement.
Ensuite, le joueur suivant est censé jouer : on récupère son coup, et une nouvelle IOException est levée. C'est cette dernière qui, par effet de bord, considère que le joueur déconnecté a abandonné, et que le joueur connecté a gagné la partie.

Ça ferrait trop de changements d'interrompre le joueur qui est un train de jouer, puis ça me paraît un peu bourrin de l'interrompre alors qu'il joue.

L'histoire des triangles blancs qui restent, je pense que c'est l'IHM qui continue des les dessiner alors qu'en théorie, elle ne devrait pas.

**Comment by MackValentine** [comment]
Du coup, la save c'est corriger dans 25bc8b2c6a468e6f23684921b153150bb4bf4498.
J'ai aussi corriger le bug du clic, quand on valider la save, ça cliquer en même temps sur retour au bureau.

**Comment by MackValentine** [comment]
Ayé, la flèche blanche est corrigé.

Bon, par contre Yohan, honnêtement, j'pense pas retravaillé l'Accueil xD.
J'essaierais de voir ce soir, mais j'promet rien ^^".

**Comment by visagey** [comment]
Yep, c'est bon la sauvegarde. 👍 
Ça a l'air sympa le Swing entre les méthodes et les attributs qui ont le même nom. 😹 

À la limite l'accueil pour les nuages c'est pas bien grave. C'était plus pour le titre, il me semblait que tu n'étais pas vraiment convaincu, et moi j'avais fait ça en mode temporaire. Du coup, comme tu veux.

C'est bon normalement pour cette histoire de journal avec le undo-redo : bb7b30b36e514da0a39854ed4350a415f0dd18a8.

**Comment by visagey** [comment]
Autre bug résolu : les piles de undo-redo n'étaient pas sauvegardées (ça me paraissait inutile), mais vu que quand l'utilisateur fait des sélections ça altère le plateau, on se retrouvait avec une belle incohérence quand on reprenait une sauvegarde dans laquelle on avait déjà commencé à faire des sélections. Corrigé dans 38e93a942a48e3758d4c5c40fd7ec9b2fc73f5ca.
