### ISSUE TITLE
A rajouter/modifier pour l'IHM

### ISSUE THREAD

**Issue by MackValentine** [lespetitspedestres/EnGarde#3]
@lespetitspedestres/team-moteur 

A faire : 
Ajouter un getOpponentPlayer()

A modifier :
isATargetableCase doit prendre en compte les cartes jouées.
Idem pour getPlayableCardsIterator.

**Comment by visagey** [comment]
Accompli dans 3ec45632477f3165f617d8c4930d1d9f0b59576e et 1a0fcd4cc03c2da8c54b67f1b3acc49d50351946.
