### ISSUE TITLE
Liste de bugs lors du déroulement des parties

### ISSUE THREAD

**Issue by Alcarioz** [lespetitspedestres/EnGarde#4]
- [x] Un joueur peut parer avec une unique carte même s'il se fait attaquer par une combinaison de plusieurs, 
 et continuer à jouer par la suite malgré sa défaite.
- [x] Lors d'une attaque directe, si un joueur clique plus de fois sur le personnage adversaire qu'il n'a de carte, 
 fait planter le jeu.
- [x] Création de pastilles rouges marquants un point gagné intempestives et infinie.
- [x] Pas moyen d'utiliser le charger lors d'une partie.
- [x] Si un premier joueur pare, la main passe à l'autre joueur, alors que le premier joueur devrait pouvoir effectuer un coup.
- [x] Attaques indirectes: gros problèmes, peut créer des attaques en utilisant des cartes qu'il ne possède pas, 
 ou en utilisant plusieurs fois une unique carte.
- [x] Pas moyen de reculer sur la case 23.

**Comment by visagey** [comment]
* d70b28656a4298bb0b64351177e6894ef4295909 : le jeu ne plante plus quand on clique plusieurs fois sur une case cliquable.
* 0db48e6ae9715256843fe67da4affe991a9dc23e : correction du bug de la case 23.

**Comment by visagey** [comment]
* 50edb7e940359193024c9bb61edcd8346319d4ef : le joueur est obligé de parrer correctement son attaque.
* 9fdb19409da25fac81c167d4e21bdb6e2d984129 : le joueur peut jouer après avoir paré.
* 4ccedb921852bd4f06a74183948e1b3802a85957 : empêche de jouer plusieurs fois la même carte pendant un tour.

Je n'ai pas réussi à reproduire le bug des pastilles rouges. C'était peut-être un effet de bord d'un autre bug.

Il reste deux autres bugs niveau **moteur** :
- [ ] Les attaques indirectes ont une puissance de 1 en trop
- [ ] Les icônes des cartes font n'importe quoi

Pour le reste, on verra ça demain, comme par exemple la fin de manche qui ne se produit jamais.

**Comment by visagey** [comment]
c27a346f01c3804b6f88a1ebbdd7513aaeeccde8 : les attaques indirectes ont la bonne force, les icônes des cartes ne font n'importe quoi.
