### ISSUE TITLE
Problème en ayant reçu une attaque indirecte

### ISSUE THREAD

**Issue by Deathleys** [lespetitspedestres/EnGarde#5]
- [ ] Si un joueur se prend une attaque indirecte avec une attaque de 2, il peut bloquer de 1 fois avec une carte correspondante, et faire 2 mouvement ensuite.
- [ ] Peut parer plusieurs cartes avec une seule. 
- [ ] Attaque directe parfois impossible. ( Souvent attaque de 5 )
- [ ] Fin du tour qui bug. Parfois les joueurs sont bloqués; ils ne peuvent rien faire, mais le jeu ne capte pas. Du coup le jeu freeze.

**Comment by Deathleys** [comment]
Peut parer plusieurs cartes avec une seule. 
Attaque directe parfois impossible. ( Souvent attaque de 5 )
Fin du tour qui bug. Parfois les joueurs sont bloqués; ils ne peuvent rien faire, mais le jeu ne capte pas. Du coup le jeu freeze.

**Comment by visagey** [comment]
Du coup la version de `isATargetableCase()` qui utilise l'automate est disponible (9675fed3c787aa652409745a3952c5a209b1284c).
J'ai aussi renforcé quelques conditions dans les méthodes de la classe Board (7dcb966fa4d8ae00485ced5f72c2e2ae6266d2a7), à voir s'il en manque toujours.
Je considère que cette issue n'est plus valide, il faudra en rouvrir une nouvelle si des bugs persistent.

Concernant le fin de tour qui bug, j'ai jeté un œil aux messages de debug dans la console, et il semblerait que ça soit un bug d'IHM, @MackValentine appelle `isEndOfRound()` un tour trop tard : la console affiche que le joueur a perdu, l'animation met "En attente du joueur suivant", et ensuite le perdant peut jouer un coup.
