### ISSUE TITLE
Problème conditions victoires.

### ISSUE THREAD

**Issue by Deathleys** [lespetitspedestres/EnGarde#7]
- [x] Des points sont parfois enlevés pendant le jeu.
- [x] En fin de round, doit jouer dernier coup inutile de temps en temps (contre IA).

**Comment by visagey** [comment]
c15801510015ead4f51cf647af13becf05910167 : correction des points qui disparaissent.
ac33b025f2a07d782d9bfa30c27625b5202518e8 : correction de la détection de la fin de manche.
